# Generated by Django 5.1.2 on 2024-10-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('substation', 'Subestação'), ('transformer', 'Transformador'), ('disconnector', 'Disjuntor'), ('fuse_key', 'Chave Fusível'), ('recloser', 'Religador Automático'), ('bus', 'Barra Elétrica')], max_length=50)),
                ('device_name', models.CharField(max_length=100)),
                ('interruptions', models.IntegerField()),
                ('resolution_time', models.FloatField()),
                ('connected_clients', models.IntegerField()),
            ],
        ),
    ]
