# Generated by Django 5.1.2 on 2024-10-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DecFecAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='connected_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DecFecAnalyzer.device'),
        ),
    ]
